### ISSUE TITLE
Absolute path

### ISSUE THREAD

**Issue by ButterSus** [sgoudham/mdbook-template#39]
_This preprocessor is great_, **but** using a _relative path_ every time you insert a component is very inconvenient.

It would be better to use absolute path from source directory like this:
```
{{ #template /absolute-path/to-directory/for-some-file.md  }}
```

If it's hard to implement absolute path, we can just pass directory in `book.toml` like this:
```toml
[preprocessor.template]
absolute-directory = "~/path-to-directory/..."
```
